http:
  middlewares:
    https-whitelist:
      ipAllowList:
        sourceRange:
          - "x.x.x.x/32"
    https-redirect:
      redirectScheme:
        scheme: https
        permanent: true

tcp:
  middlewares:
    tcp-whitelist:
      ipAllowList:
        sourceRange:
          - "x.x.x.x/32"

tls:
  certificates:
    - certFile: /etc/certs/cert.pem
      keyFile: /etc/certs/key.pem
