global:
  sendAnonymousUsage: false

api:
  dashboard: true
  debug: false

log:
  level: DEBUG
  # level: ERROR

accessLog: {}

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: wordpress-network
  file:
    filename: /etc/traefik/dynamic_conf/dynamic_conf.yml

entryPoints:
  http:
    address: ':80'
  https:
    address: ':443'
  mysql:
    address: ':3306/tcp'
